### ISSUE TITLE
成都发展实录

### ISSUE THREAD

**Issue by BetterBetterChina** [BetterBetterChina/CityDeveloping#21]
2020年05月21日
[成都联手人民银行出台规划：2022年建成区域金融科技中心](http://www.nbd.com.cn/articles/2020-05-20/1436527.html)
> 中国人民银行成都分行营业管理部联合召开新闻发布会，正式发布《成都市金融科技发展规划（2020-2022年）》（以下简称《规划》），这也是全国首个由地方政府和人民银行联合发布实施的金融科技发展规划。

> 《规划》中提出，到2022年底前，努力把成都建设成为具有国际影响力的区域金融科技中心，构建“成都特色、全国影响、国内示范、国际同步”的金融科技创新示范体系，确立成都金融科技在中西部地区领先、全国一流的地位。

**Comment by xgdgsc** [comment]
我看你现在是改issue的description更新的，这样不方便只订阅关注的城市吧，建议用comment更新
